{
  imports = [
    ./clipper.nix
    ./syncthing.nix
    ./polybar.nix
    ./hyprpaper.nix
    ./gammastep.nix
    ./waybar
    ./mako.nix
    ./copyq.nix
    ./gtklock.nix
    ./fcitx5.nix
    ./playerctld.nix
    ./nix-home-manager-gc.nix
    ./network-manager-applet.nix
    ./aria2
    ./easyeffects.nix
    ./flameshot.nix
  ];
}
