{
  imports = [
    ./emacs
    ./networkmanager-dmenu.nix
    ./hyprland
    ./keychain.nix
    ./navi.nix
    ./set-theme
    ./i3
    ./nixGL.nix
    ./hm-switch.nix
    ./fontconfig
    ./zsh
    ./zsh/zimfw.nix
    ./git
    ./gh.nix
    ./jj
    ./python-dev-tools
    ./yazi
    ./alacritty.nix
    ./foot.nix
    ./vim
    ./tmux
    ./fzf.nix
    ./powerline
    ./jetbrains
    ./firefox
    ./nvim
    ./baidupcs-go.nix
    ./opencode.nix
    ./crush.nix
    ./codex.nix
    ./ai-agent-common
    ./claude-code.nix
    ./obsidian.nix
    ./ergodox.nix
  ];
}
