{
  imports = [
    ./gateway
    ./nix-serve
    ./zrepl
    ./docker.nix
    ./docker-rootless.nix
    ./autofs
    ./monitoring/metrics.nix
    ./monitoring/monitoring.nix
    ./networking/headscale.nix
    ./networking/tailscale.nix
    ./ups
    ./smartd.nix
    ./lock.nix
    ./aria2
    ./ariang.nix
    ./openrgb.nix
    ./vsftpd
    ./proxmox
  ];
}
