keys:
  - &users:
    - &sinkerine E51ECE14AD2CBB96D4FC42E25C8651C428B9DF03
  - &hosts:
    - &kazuki age1sc2gp8d40y7d9engfqhydg5v6mcg0aj40x3yccndzh7ruxvj63cqcpax76
    - &asako age1kez9h9hmz4amrq5phv8cwv3d04l775ctzaqgrd7q9u70hp6s0ehsjp5wk8
    - &sachi age147zmk06prg2864yym9tcg5z9vl9ldykv5zkwuuefuy85q994qp3sjh3lfd
creation_rules:
  - path_regex: hosts/kazuki/secrets\.yaml$
    pgp: *sinkerine
    age: *kazuki
  - path_regex: hosts/asako/secrets\.yaml$
    pgp: *sinkerine
    age: *asako
  - path_regex: hosts/sachi/secrets\.yaml$
    pgp: *sinkerine
    age: *sachi
  - path_regex: hosts/sachi/smbpasswd$
    pgp: *sinkerine
    age: *sachi
  - path_regex: hosts/features/app/autofs/cifs-secrets.txt
    age: "age1sc2gp8d40y7d9engfqhydg5v6mcg0aj40x3yccndzh7ruxvj63cqcpax76,age1kez9h9hmz4amrq5phv8cwv3d04l775ctzaqgrd7q9u70hp6s0ehsjp5wk8"
    pgp: *sinkerine
  - path_regex: hosts/asako/zrepl/.*\.(crt|key)$
    pgp: *sinkerine
    age: *asako
