keys:
  - &users:
    - &sinkerine 242F455F27D96A97A2FB9DA1FB938BEA0458EF24
  - &hosts:
    - &kazuki age1sc2gp8d40y7d9engfqhydg5v6mcg0aj40x3yccndzh7ruxvj63cqcpax76
    - &asako age1kez9h9hmz4amrq5phv8cwv3d04l775ctzaqgrd7q9u70hp6s0ehsjp5wk8
creation_rules:
  - path_regex: hosts/kazuki/secrets.yaml$
    pgp: *sinkerine
    age: *kazuki
  - path_regex: hosts/asako/secrets.yaml$
    pgp: *sinkerine
    age: *asako
