{
 "title": "zrepl",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "prom_job_name", "label": "Prometheus Job Name", "query": "label_values(up, job)" },
   {
    "name": "zrepl_job_name",
    "label": "Zrepl Job Name",
    "query": "label_values(zrepl_replication_filesystem_errors{job=\"zrepl\"}, zrepl_job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "content": "# zrepl Prometheus Metrics\n\nzrepl exposes Prometheus metrics and ships with this Grafana dashboard.\nThe exported metrics are suitable for health checks:\n\n* The log should generally be warning & error-free\n  * The `Log Messages that require attention` graph visualizes log message at levels that generally indicate problems.\n* The number of goroutines should not grow unboundedly over time.\n  * During replication, the number of goroutines can be way higher than during idle time.\n  * If the goroutine count grows with each replication, there is clearly a goroutine leak. Please open a bug report.\n* Memory consumption should not grow unboundedly over time.\n  * Note that the Go runtime pre-allocates some of its heap from the OS.\n  * zrepl actually uses much less memory than allocated from the OS.\n  * Since Go 1.11, Go pre-allocates more aggressively.\n* Monitor that some data is replicated, although that metric does not guarantee that replication was successful.\n\n**In general, note that the exported metrics are not stable unless declared otherwise.**"
  },
  {
   "title": "Failed replications $zrepl_job_name",
   "type": "singlestat",
   "description": "Number of filesystems that failed replications",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 10 },
   "repeat": "zrepl_job_name",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "zrepl_replication_filesystem_errors{job=\"zrepl\",zrepl_job=\"$zrepl_job_name\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "zrepl Instances Up",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sgn(zrepl_start_time{job='zrepl'})",
     "legendFormat": "{{instance}}@version={{raw}}"
    }
   ]
  },
  {
   "title": "active tasks tracked by the zrepl trace module (should not grow unboundedly)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "zrepl_trace_active_tasks" }
   ]
  },
  {
   "title": "Daily Replication Data Volume",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(zrepl_replication_bytes_replicated{job='zrepl'}[1d])) by (zrepl_job)",
     "legendFormat": "zrepl_job={{zrepl_job}}"
    }
   ]
  },
  {
   "title": "Log Messages that require attention",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(zrepl_daemon_log_entries{job='zrepl',level=~'warn|error'}[1m])"
    }
   ]
  },
  {
   "title": "Replication Data Rate and Volume(over last 10min)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zrepl_replication_bytes_replicated{job='zrepl'}[10m])) by (zrepl_job)",
     "legendFormat": "replication data ratein last 10min zrepl_job={{zrepl_job}}te zrepl_job={{zrepl_job}}"
    },
    {
     "expr": "sum(increase(zrepl_replication_bytes_replicated{job='zrepl'}[10m])) by (zrepl_job)",
     "legendFormat": "replicated bytes in last 10min zrepl_job={{zrepl_job}}"
    }
   ]
  },
  {
   "title": "Log Activity (without internal jobs)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(zrepl_daemon_log_entries{job='zrepl',zrepl_job=~\"^[^_].*\"}[1m])) by (instance,zrepl_job)"
    }
   ]
  },
  {
   "title": "Go Memory Allocations (should not grow unboundedly)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job='zrepl'}"
    }
   ]
  },
  {
   "title": "zfs abstractions cache entry count (should not be zero and not grow unboundedly)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zrepl_endpoint_abstractions_cache_entry_count"
    }
   ]
  },
  {
   "title": "Memory Allocated by the Go runtime from the OS (should not grow unboundedly)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{job='zrepl'}"
    }
   ]
  },
  {
   "title": "number of goroutines (should not grow unboundedly)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_goroutines{job='zrepl'}" }
   ]
  }
 ]
}